version: "3.1"

services:
  tspoo-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: 'tspoo-db'
      MYSQL_ROOT_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'